Repository TEALSK12/introduction-to-computer-science, pull requests merged in 2020-08, with the labels that each got.

#234 Fix link
  do_now_13.md
  docs/do_now_13.md.html
Labels: Bug

#236 Update Snap 2.5 Slide Deck
  slidedecks/TEALS SNAP 2.5.pptx
Labels: Bug

#238 Unit 4 Slide Decks
  Changelog.md
  curriculum_map.md
  docs/Changelog.md.html
  docs/curriculum_map.md.html
  docs/slidedecks/TEALS SNAP 4.1.pptx
  docs/slidedecks/TEALS SNAP 4.2.pptx
  docs/slidedecks/TEALS SNAP 4.3.pptx
  docs/slidedecks/TEALS SNAP 4.4.pptx
  docs/slidedecks/TEALS SNAP 4.5.pptx
  slidedecks/TEALS SNAP 4.1.pptx
  slidedecks/TEALS SNAP 4.2.pptx
  slidedecks/TEALS SNAP 4.3.pptx
  slidedecks/TEALS SNAP 4.4.pptx
  slidedecks/TEALS SNAP 4.5.pptx
Labels: Feature

#239 5.2 SLide deck link fix
  curriculum_map.md
  docs/Changelog.md.html
  docs/curriculum_map.md.html
  docs/intro-book-complete.pdf
  docs/slidedecks/TEALS SNAP 2.5.pptx
Labels: Bug

#240 Add description and solution for Do Now 2.4
  do_now_24.md
  lesson_24.md
  slidedecks/TEALS SNAP 2.4.pptx
Labels: Bug, IntroCS.1

#241 build with changes to 2.4 Do now
  Changelog.md
  curriculum_map.md
  do_now_46.md
  docs/Changelog.md.html
  docs/curriculum_map.md.html
  docs/do_now_24.md.html
  docs/do_now_46.md.html
  docs/lesson_24.md.html
  docs/lesson_46.md.html
  docs/project_4.md.html
  docs/slidedecks/TEALS SNAP 2.4.pptx
  docs/slidedecks/spaceman.pptx
  lesson_46.md
  project_4.md
  slidedecks/spaceman.pptx
Labels: Bug, Feature

#242 Added Instructions to Spaceman
  Projects/Projects Word/Platform_Game_Planning_Worksheet.docx
  docs/Projects/Projects Word/Platform_Game_Planning_Worksheet.docx
  docs/lesson_35.md.html
  docs/lesson_46.md.html
  lesson_35.md
  lesson_46.md
Labels: Bug

#243 Updated PBJ video
  Coordinates.png
  curriculum_map.md
  do_now_05.md
  do_now_11.md
  docs/lesson_02.md.html
  lab_05.md
  lab_11.md
  lesson_02.md
  lesson_05.md
  slidedecks/TEALS SNAP 0.5.pptx
Labels: Feature

#246 Vol Suggestion updates, add resources, ext. angle, scaffold, formatting
  .vscode/settings.json
  Changelog.md
  SnapCloud.png
  SnapSignUp.png
  Unit 0/IntrotoCSSyllabusExample.docx
  Unit 0/Lab 0.4.docx
  Unit 0/Lab 0.4.pdf
  Unit 0/Student Experiences Survey.docx
  Unit 0/Student Experiences Survey.pdf
  Unit 0/lab_04.docx
  Unit 0/lab_04.pdf
  Unit 0/lab_05.docx
  Unit 0/lab_05.pdf
  Unit 1 PDF/Lab 1.1 Welcome To SNAP.pdf
  Unit 1 Word/Lab 1.1 Welcome To SNAP.docx
  custom-reference.docx
  do_now_05.md
  do_now_13.md
  docs/.vscode/settings.json
  docs/Changelog.md.html
  docs/SnapCloud.png
  docs/SnapSignUp.png
  docs/Unit 0/IntrotoCSSyllabusExample.docx
  docs/Unit 0/Student Experiences Survey.docx
  docs/Unit 0/Student Experiences Survey.pdf
  docs/Unit 0/lab_04.docx
  docs/Unit 0/lab_04.pdf
  docs/Unit 0/lab_05.docx
  docs/Unit 0/lab_05.pdf
  docs/Unit 1 PDF/Lab 1.1 Welcome To SNAP.pdf
  docs/Unit 1 Word/Lab 1.1 Welcome To SNAP.docx
  docs/custom-reference.docx
  docs/do_now_05.md.html
  docs/do_now_13.md.html
  docs/lab_04.md.html
  docs/lab_05.md.html
  docs/lab_12.md.html
  docs/lab_13.md.html
  docs/lesson_01.md.html
  docs/lesson_04.md.html
  docs/lesson_05.md.html
  docs/lesson_11.md.html
  docs/lesson_12.md.html
  docs/lesson_13.md.html
  docs/lesson_46.md.html
  docs/slidedecks/TEALS SNAP 0.1.pptx
  lab_04.md
  lab_05.md
  lab_12.md
  lab_13.md
  lesson_01.md
  lesson_04.md
  lesson_05.md
  lesson_11.md
  lesson_12.md
  lesson_13.md
  lesson_46.md
  slidedecks/TEALS SNAP 0.1.pptx
Labels: Feature, IntroCS.1
