Repository TEALSK12/introduction-to-computer-science, pull requests merged in 2020-09, with the labels that each got.

#250 Fix typos in Lab 1.3
  Unit 1 PDF/Lab 1.3 Squares Triangles.pdf
  Unit 1 Word/Lab 1.3 Squares Triangles.docx
  lab_13.md
Labels: Bug

#251 Added VIdeo Quizzes
  Video Resources.md
  docs/Video Resources.md.html
  docs/lesson_01.md.html
  docs/lesson_02.md.html
  docs/lesson_03.md.html
  docs/lesson_04.md.html
  docs/lesson_05.md.html
  docs/lesson_11.md.html
  docs/lesson_12.md.html
  docs/lesson_13.md.html
  docs/lesson_14.md.html
  docs/lesson_21.md.html
  docs/lesson_22.md.html
  docs/lesson_23.md.html
  docs/lesson_24.md.html
  docs/lesson_25.md.html
  docs/lesson_31.md.html
  docs/lesson_32.md.html
  docs/lesson_33.md.html
  docs/lesson_34.md.html
  lesson_01.md
  lesson_02.md
  lesson_03.md
  lesson_04.md
  lesson_05.md
  lesson_11.md
  lesson_12.md
  lesson_13.md
  lesson_14.md
  lesson_21.md
  lesson_22.md
  lesson_23.md
  lesson_24.md
  lesson_25.md
  lesson_31.md
  lesson_32.md
  lesson_33.md
  lesson_34.md
Labels: Feature

#261 Update Change Log
  Changelog.md
  docs/Changelog.md.html
  docs/styles/curriculum.css
  styles/curriculum.css
Labels: Feature

#262 Lab04 and Lab11 Updates from Teacher Feedback
  Unit 0/lab_04.docx
  Unit 0/lab_04.pdf
  Unit 1 PDF/Lab 1.1 Welcome To SNAP.pdf
  Unit 3 PDF/Lab 3.4 The Technicolor Window.pdf
  Unit 3 Word/Lab 3.4 The Technicolor Window.docx
  docs/Unit 0/lab_04.docx
  docs/Unit 0/lab_04.pdf
  docs/Unit 1 PDF/Lab 1.1 Welcome To SNAP.pdf
  docs/Unit 3 PDF/Lab 3.4 The Technicolor Window.pdf
  docs/Unit 3 Word/Lab 3.4 The Technicolor Window.docx
  docs/lab_04.md.html
  docs/lesson_34.md.html
  docs/min_42.png
  lab_04.md
  lesson_34.md
  min_42.png
Labels: IntroCS.1

#264 Lab formatting Consistency across all labs
  Unit 0/lab_04.docx
  Unit 0/lab_04.pdf
  do_now_11.md
  docs/Unit 0/lab_04.docx
  docs/Unit 0/lab_04.pdf
  docs/do_now_11.md.html
  docs/lab_04.md.html
  docs/lab_05.md.html
  docs/lab_11.md.html
  docs/lab_12.md.html
  docs/lab_13.md.html
  docs/lab_14.md.html
  docs/lab_21.md.html
  docs/lab_22.md.html
  docs/lab_23.md.html
  docs/lab_24.md.html
  docs/lab_25.md.html
  docs/lab_31.md.html
  docs/lab_32.md.html
  docs/lab_33.md.html
  docs/lab_34.md.html
  docs/lab_42.md.html
  docs/lab_43.md.html
  docs/lab_44.md.html
  docs/lab_45.md.html
  docs/lesson_11.md.html
  docs/lesson_12.md.html
  docs/slidedecks/TEALS SNAP 1.1.pptx
  docs/slidedecks/TEALS SNAP 1.2.pptx
  docs/slidedecks/TEALS SNAP 1.4.pptx
  lab_04.md
  lab_05.md
  lab_11.md
  lab_12.md
  lab_13.md
  lab_14.md
  lab_21.md
  lab_22.md
  lab_23.md
  lab_24.md
  lab_25.md
  lab_31.md
  lab_32.md
  lab_33.md
  lab_34.md
  lab_42.md
  lab_43.md
  lab_44.md
  lab_45.md
  lesson_11.md
  lesson_12.md
  slidedecks/TEALS SNAP 1.1.pptx
  slidedecks/TEALS SNAP 1.2.pptx
  slidedecks/TEALS SNAP 1.4.pptx
Labels: Bug

#263 Wording fixes based on teacher feedback and Helping Trios structured for remote delivery
  docs/helping_trios.md.html
  docs/helping_trios_handout.md.html
  docs/lesson_11.md.html
  docs/lesson_12.md.html
  docs/lesson_53.md.html
  docs/slidedecks/TEALS SNAP 0.4.pptx
  docs/slidedecks/TEALS SNAP 0.5.pptx
  helping_trios.md
  helping_trios_handout.md
  lesson_11.md
  lesson_12.md
  lesson_53.md
  slidedecks/TEALS SNAP 0.4.pptx
  slidedecks/TEALS SNAP 0.5.pptx
Labels: Bug, Feature
