Repository TEALSK12/introduction-to-computer-science, pull requests merged in 2020-11, with the labels that each got.

#279 fix lab_32 syntax errors
  lab_32.md
Labels: Bug

#280 Lesson and Labs 4.1-4.5 Updates and Answer Keys
  Changelog.md
  Unit 4 PDF/Lab 4.2 You Talkin To Me.pdf
  Unit 4 PDF/Lab 4.3 Guess Who.pdf
  Unit 4 PDF/Lab 4.4 Number Cruncher.pdf
  Unit 4 PDF/Lab 4.5 Its Around Here Somewhere.pdf
  Unit 4 Word/Lab 4.2 You Talkin To Me.docx
  Unit 4 Word/Lab 4.3 Guess Who.docx
  Unit 4 Word/Lab 4.4 Number Cruncher.docx
  Unit 4 Word/Lab 4.5 Its Around Here Somewhere.docx
  docs/Changelog.md.html
  docs/Unit 4 PDF/Lab 4.2 You Talkin To Me.pdf
  docs/Unit 4 PDF/Lab 4.3 Guess Who.pdf
  docs/Unit 4 PDF/Lab 4.4 Number Cruncher.pdf
  docs/Unit 4 PDF/Lab 4.5 Its Around Here Somewhere.pdf
  docs/Unit 4 Word/Lab 4.2 You Talkin To Me.docx
  docs/Unit 4 Word/Lab 4.3 Guess Who.docx
  docs/Unit 4 Word/Lab 4.4 Number Cruncher.docx
  docs/Unit 4 Word/Lab 4.5 Its Around Here Somewhere.docx
  docs/lab_32.md.html
  docs/lab_42.md.html
  docs/lab_43.md.html
  docs/lab_44.docx
  docs/lab_44.md.html
  docs/lab_45.md.html
  docs/lesson_41.md.html
  docs/lesson_42.md.html
  docs/lesson_43.md.html
  docs/lesson_44.md.html
  docs/lesson_45.md.html
  lab_42.md
  lab_43.md
  lab_44.md
  lab_45.md
  lesson_41.md
  lesson_42.md
  lesson_43.md
  lesson_44.md
  lesson_45.md
Labels: Feature, IntroCS.1

#283 Final project html build
  Final Project Development Plan.docx
  Final Project Plan Organizer.docx
  Projects/Projects PDF/Project 6 Final Project.pdf
  Projects/Projects Word/Project 6 Final Project.docx
  Unit 6 PDF/Final Project Plan Organizer.pdf
  Unit 6 PDF/Project Feedback Form.pdf
  Unit 6 PDF/TEALS Final Project Design Steps.pdf
  Unit 6 Word/Final Project Plan Organizer.docx
  Unit 6 Word/Project Feedback Form.docx
  Unit 6 Word/TEALS Final Project Design Steps.docx
  curriculum_map.md
  docs/Projects/Projects PDF/Project 6 Final Project.pdf
  docs/Projects/Projects Word/Project 6 Final Project.docx
  docs/Unit 6 PDF/Final Project Plan Organizer.pdf
  docs/Unit 6 PDF/Project Feedback Form.pdf
  docs/Unit 6 PDF/TEALS Final Project Design Steps.pdf
  docs/Unit 6 Word/Final Project Plan Organizer.docx
  docs/Unit 6 Word/Project Feedback Form.docx
  docs/Unit 6 Word/TEALS Final Project Design Steps.docx
  docs/curriculum_map.md.html
  docs/lesson_61.md.html
  docs/lesson_62.md.html
  docs/lesson_63.md.html
  docs/lesson_64.md.html
  docs/lesson_65.md.html
  docs/lesson_66.md.html
  docs/project_6.md.html
  lesson_61.md
  lesson_62.md
  lesson_63.md
  lesson_64.md
  lesson_65.md
  lesson_66.md
  project_6.md
Labels: Bug, IntroCS.1

#284 Week of 11-23 Updates
  Changelog.md
  Grudgeball.md
  Unit 1 PDF/Lab 1.4 Sprites in Action.pdf
  Unit 1 Word/Lab 1.4 Sprites in Action.docx
  broadcast_and_wait.png
  do_now_32.md
  docs/Changelog.md.html
  docs/Grudgeball.md.html
  docs/Unit 1 PDF/Lab 1.4 Sprites in Action.pdf
  docs/Unit 1 Word/Lab 1.4 Sprites in Action.docx
  docs/broadcast_and_wait.png
  docs/do_now_32.md.html
  docs/intro-book-complete.md.html
  docs/lab_14.md.html
  docs/lab_51.md.html
  docs/lesson_14.md.html
  docs/lesson_32.md.html
  docs/lesson_63.md.html
  docs/lesson_64.md.html
  docs/lesson_65.md.html
  docs/next_costume.png
  docs/project_3.md.html
  docs/switch_costume.png
  lab_14.md
  lab_51.md
  lesson_14.md
  lesson_21.html
  lesson_32.md
  lesson_63.md
  lesson_64.md
  lesson_65.md
  next_costume.png
  project_3.md
  switch_costume.png
Labels: Bug
